# Common scl-kit complex configuration
################################################################################
CONFIG *= \
    embed_manifest_exe \
    exceptions \
    largefile \
    precompile_header \
    rtti \
    silent \
    stl \
    thread \
    warn_on \

!win32-msvc* {
    CONFIG -= \
        debug_and_release \
        debug_and_release_target \

#    CONFIG *= \
#        object_parallel_to_source \ // The file paths are too long
#        object_with_source \
}

unset(QT)

DEFINES *= QT_NO_DEPRECATED_WARNINGS

# Features addition
################################################################################
QMAKEFEATURES = $${PWD}/project/qmake/features

CONFIG *= \
    auto_version \      # Runtime/compile versioning
    complex_paths \     # Common build and destination paths
    module_depends \    # Resolving of module dependencies
    ndebug \            # Add NDEBUG for release
