site_name: ScL Toolkit
site_description: C++20 header-only toolkit
docs_dir: doc/mkdocs
site_dir: public

theme:
  name: material
  palette:
    scheme: default
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes

extra:
  version:
    provider: mike
    default: latest

plugins:
  - search
  - mkdoxy:
      projects:
        scl-utility:
          src-dirs: module/utility/src
          full-doc: True
          doxy-cfg:
            PROJECT_NAME: SCL.Utility
            RECURSIVE: "YES"
            FILE_PATTERNS: "*.h *.hpp *.hh"
            EXTRACT_ALL: "NO"
            HIDE_UNDOC_MEMBERS: "YES"
            HIDE_UNDOC_CLASSES: "YES"
            HIDE_UNDOC_NAMESPACES: "YES"
            EXCLUDE_SYMBOLS: "*::detail *::detail::*"
        scl-feature:
          src-dirs: module/feature/src
          full-doc: True
          doxy-cfg:
            PROJECT_NAME: SCL.Feature
            RECURSIVE: "YES"
            FILE_PATTERNS: "*.h *.hpp *.hh"
            EXTRACT_ALL: "NO"
            HIDE_UNDOC_MEMBERS: "YES"
            HIDE_UNDOC_CLASSES: "YES"
            HIDE_UNDOC_NAMESPACES: "YES"
            EXCLUDE_SYMBOLS: "*::detail *::detail::*"

nav:
  - Home: index.md
